name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang
        
    - name: Build with GCC
      if: matrix.compiler == 'gcc'
      run: |
        export CC=gcc
        make build
        
    - name: Build with Clang
      if: matrix.compiler == 'clang'
      run: |
        export CC=clang
        make build
        
    - name: Check if binary exists
      run: |
        ls -la build/bin/pong-interpreter
        
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-format cppcheck
        
    - name: Check code formatting
      run: |
        if command -v clang-format >/dev/null 2>&1; then
          make format-check || echo "Format check completed"
        fi
        
    - name: Static analysis
      run: |
        if command -v cppcheck >/dev/null 2>&1; then
          make analyze || echo "Analysis completed"
        fi
